# Generated by Django 5.0 on 2023-12-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="create_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="dead_line",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="todo",
            name="finshed_at",
            field=models.DateField(null=True),
        ),
    ]
